config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  # resources :articles do
  #   resources :comments
  # end
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to:'sessions#create'
  delete 'login', to: 'sessions#destroy'
  jsonapi_resources :users
  jsonapi_resources :articles do 
    jsonapi_resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase}
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
  VAILD_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 105}, format: {with: VAILD_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include Pundit, JSONAPI::ActsAsResourceController

    protect_from_forgery with: :null_session

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private
  
    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def index
        @comment = Comment.new
        @article = Article.find(params[:article_id])
        @comments = @article.comments  
        render json: @comments
    end

    def new

    end

    def edit

    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
        if logged_in?
            redirect_to articles_path 
        else
            redirect_to login_path
        end
    end

    def about        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def new
    
  end

  def create
    
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
      
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user)
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}"
        image_tag(gravatar_url, alt: user.username)
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan="3">Actions</th>
            <th>Written By</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |item| %>
                    <tr>
                        <td><%= item.title %></td>
                        <td><%= item.description %></td>
                        <td><%= link_to 'Show', article_path(item) %></td>
                        <% if logged_in? && (item.user == current_user || current_user.admin?)%>
                            <td><%= link_to 'Edit', edit_article_path(item) %></td>
                            <td><%= link_to 'Delete', article_path(item), method: :delete, data: {confirm: "are you sure"} %></td>
                        <% end %>
                        <td><%= item.user.username if item.user%></td>
                    </tr>
        <% end %>
    </tbody>
</table>
<br>
<%= link_to 'Bloggers', users_path%>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <h2>There following errors are preventing the article to be saved</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg%></li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>
    <p>
        <%= f.label :title %>
        <br>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :description %>
        <br>
        <%= f.text_area :description %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Cancel and return to articles listing', articles_path%>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>
<%= will_paginate @articles%>
<%= render 'article' %>
<p>
<%= link_to "Create new article", new_article_path%>
</p>

app/views/articles/new.html.erb
<h1>Create new article</h1>

<%= render 'form' %>

<%= link_to 'Return to articles listing', articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>
<p><strong>Title: </strong><%= @article.title%></p>
<p><strong>Description: </strong> <%= @article.description%></p>
<p><strong>Written by</strong> <%= @article.user.username if @article.user%></p>
<p> <%= link_to gravatar_for(@article.user), user_path(@article.user)  %> </p>

<% if logged_in? && (@article.user == current_user || current_user.admin?)%>
<%= link_to 'Edit', edit_article_path(@article) %> | 
<%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "are you sure"} %> |
<% end %>

<%= render @article.comments%> 
<%= link_to 'Return to articles listing', articles_path%>

app/views/comments/_comment.html.erb
<article>
    <p> 
        <%= comment.description %>
    </p>
</article>

app/views/comments/index.html.erb
<h1> Comments for the post </h1>
    <h2><%= @article.title %></h2>
    <br>
<% if @comments %>
<% @comments.each do |item|%>
    <%= item.description %>
    <%= item.user.username %>
    <hr>
<% end %>
<% end %>

<%= form_with(url: "#{article_path(@article)}/comments", method: :post, local: true) do |f| %>
    <p>
        <%= f.label :comment %>
        <br>
        <%= f.text_area :description %>
    </p>

    <p>
        <%= f.submit%>
    </p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
    <%= msg%>
<% end %>

app/views/layouts/_navigation.html.erb
<h1>Hello</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= link_to 'Articles listing', articles_path%> |
<%= link_to 'Home Page', root_path%> |
<%= link_to 'Sign Up', signup_path %> |
<%= link_to 'Bloggers', users_path %>

app/views/pages/home.html.erb
<h1> This is the home page </h1>

<%= link_to 'Articles listing', articles_path%> |
<%= link_to 'About Page', about_path%> |
<%= link_to 'Sign Up', signup_path %> |
<%= link_to 'Bloggers', users_path %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <h2>There following errors are preventing the user to be saved</h2>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg%></li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
    <p>
        <%= f.label :username %>
        <br>
        <%= f.text_field :username, placeholder: "Enter a username" %>
    </p>

    <p>
        <%= f.label :email %>
        <br>
        <%= f.email_field :email, placeholder: "Enter your email address" %>
    </p>

    <p>
        <%= f.label :password %>
        <br>
        <%= f.password_field :password, placeholder: "Enter your password" %>
    </p>

    <p>
        <%= f.submit(@user.new_record? ? "Sign up" : "Update account" )%>
    </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your alpha block</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Alpha Bloggers</h1>

<%= will_paginate @articles%>


<table>
    <thead>
        <tr>
            <th>Username</th>
            <th>Profile pic</th>
            <th>Number of articles written</th>
            <th colspan = "2">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
                    <tr>
                        <td><%= link_to user.username, user %></td>
                        <td><%= link_to gravatar_for(user), user %></td>
                        <td><%= pluralize(user.articles.count, "articles") %></td>
                        <td><%= link_to 'View profile', user %></td>
                        <% if logged_in? && (user == current_user || current_user.admin?) %>
                        <td>
                            <%= link_to 'Edit profile', edit_user_path(user)%>
                            <td><%= link_to 'Delete profile', user, method: :delete, data: { confirm: "Are you sure?"} %></td>
                        </td>
                        <% end %>
                    </tr>
        <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<h1>Signup for alpha block</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username%>'s profile</h1>

<%= gravatar_for @user%>
<br>

<% if logged_in? && @user == current_user %>
    <%= link_to "Edit your profile", edit_user_path(@user)%>
<% end %>

<h3>Articles</h3>

<%= render 'articles/article' %>